# Generated by Django 2.1.7 on 2019-11-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_post1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
